name: Post Activity History to all Users

on:
  schedule:
    - cron:  30 22 9 8 *
  workflow_dispatch:

jobs:
  Read-CSV:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse CSV
        id: parse-csv
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HACKFORLA_GRAPHQL_TOKEN }}
          script: |
            const script = require('./github-actions/activity-trigger/first-post-to-skills-issue.js')
            return script({g: github, c: context})